"""Hand-checked tests for the evidential-classification decomposition.

The fixture has 5 points and ``K=3``. Expected ``A_hat`` / ``E_hat``
values were generated by running the closed-form formulae through
``numpy``/``math.log`` and locking the resulting ``repr()`` strings
in this file. A regression in the formulae or in the wrapper will
fail one of these to ``atol=1e-6``.

Decomposition under test (Sensoy et al. 2018):

    alpha_0 = sum_k alpha[k]
    p_hat = alpha / alpha_0
    E_hat = K / alpha_0                                 (mass-based epistemic)
    cross_entropy:
        A_hat = -sum_k p_hat[k] log p_hat[k]            (entropy in nats)
        H_hat = p_hat                                    (soft (N, K))
    zero_one:
        A_hat = 1 - max_k p_hat[k]
        H_hat = argmax_k p_hat[k]                        (hard (N,) int64)
"""

from __future__ import annotations

import numpy as np
import pytest

from probly.quantification.decomposition import (
    OutputSchema,
    decompose_from_schema,
    evidential_decomposition,
)

# ---------------------------------------------------------------------------
# Fixture: 5 points, K=3.
#
#   i=0  alpha=[10, 1, 1]    -> alpha_0=12,  p_hat=[10/12, 1/12, 1/12]
#   i=1  alpha=[1, 1, 1]     -> alpha_0=3,   p_hat uniform
#   i=2  alpha=[100,100,100] -> alpha_0=300, p_hat uniform
#   i=3  alpha=[50, 49, 1]   -> alpha_0=100, p_hat=[0.50, 0.49, 0.01]
#   i=4  alpha=[2, 2, 2]     -> alpha_0=6,   p_hat uniform
# ---------------------------------------------------------------------------

_ALPHA = np.array(
    [
        [10.0, 1.0, 1.0],
        [1.0, 1.0, 1.0],
        [100.0, 100.0, 100.0],
        [50.0, 49.0, 1.0],
        [2.0, 2.0, 2.0],
    ],
    dtype=np.float64,
)
# evidence = alpha_0 - K (the softplus(logit) sum). Cached only;
# unused in the decomposition formulas. We pass it through to verify
# the dispatcher accepts it without entering the math.
_EVIDENCE = _ALPHA.sum(axis=1) - _ALPHA.shape[1]

_EXPECTED_E_HAT = np.array(
    [0.25, 1.0, 0.01, 0.03, 0.5],
    dtype=np.float32,
)

# Cross-entropy A_hat is the categorical entropy of p_hat (in nats).
# Values locked from `numpy`'s computation; any drift > atol=1e-6 is
# a regression.
_EXPECTED_A_HAT_CE = np.array(
    [
        0.5660857389596289,  # -((10/12)ln(10/12) + 2*(1/12)ln(1/12))
        1.0986122886681096,  # ln(3)
        1.0986122886681096,  # ln(3)
        0.7421667371998113,  # -(0.50 ln 0.50 + 0.49 ln 0.49 + 0.01 ln 0.01)
        1.0986122886681096,  # ln(3)
    ],
    dtype=np.float64,
)

# Zero-one A_hat = 1 - max_k p_hat[k]. argmax tie-break: numpy's smallest
# index (0 for the uniform fixtures).
_EXPECTED_A_HAT_ZO = np.array(
    [
        1.0 - 10.0 / 12.0,  # = 1/6
        2.0 / 3.0,  # uniform: 1 - 1/3
        2.0 / 3.0,
        0.50,  # 1 - 0.50
        2.0 / 3.0,
    ],
    dtype=np.float64,
)
_EXPECTED_H_HAT_ZO = np.array([0, 0, 0, 0, 0], dtype=np.int64)

# H_hat for cross-entropy is the soft p_hat array.
_EXPECTED_H_HAT_CE = (_ALPHA / _ALPHA.sum(axis=1, keepdims=True)).astype(np.float32)


# ---------------------------------------------------------------------------
# Direct-call tests
# ---------------------------------------------------------------------------


def test_evidential_cross_entropy_matches_locked_values() -> None:
    out = evidential_decomposition(_ALPHA, _EVIDENCE, "cross_entropy")
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.float32
    assert out["A_hat"].shape == (5,)
    assert out["E_hat"].shape == (5,)
    assert out["H_hat"].shape == (5, 3)
    np.testing.assert_allclose(out["A_hat"], _EXPECTED_A_HAT_CE, atol=1e-6)
    np.testing.assert_allclose(out["E_hat"], _EXPECTED_E_HAT, atol=1e-6)
    np.testing.assert_allclose(out["H_hat"], _EXPECTED_H_HAT_CE, atol=1e-6)


def test_evidential_zero_one_matches_locked_values() -> None:
    out = evidential_decomposition(_ALPHA, _EVIDENCE, "zero_one")
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.int64
    assert out["A_hat"].shape == (5,)
    assert out["E_hat"].shape == (5,)
    assert out["H_hat"].shape == (5,)
    np.testing.assert_allclose(out["A_hat"], _EXPECTED_A_HAT_ZO, atol=1e-6)
    np.testing.assert_allclose(out["E_hat"], _EXPECTED_E_HAT, atol=1e-6)
    np.testing.assert_array_equal(out["H_hat"], _EXPECTED_H_HAT_ZO)


def test_evidential_zero_one_argmax_tiebreak_uses_smallest_index() -> None:
    """Locked: argmax tie-break follows ``numpy.argmax`` (smallest index).

    Three of the five fixture points are uniform (alpha rows
    ``[1,1,1]``, ``[100,100,100]``, ``[2,2,2]``); their ``H_hat``
    must be 0 by the smallest-index convention.
    """
    out = evidential_decomposition(_ALPHA, _EVIDENCE, "zero_one")
    np.testing.assert_array_equal(out["H_hat"][[1, 2, 4]], np.array([0, 0, 0]))


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def test_evidential_rejects_non_positive_alpha() -> None:
    bad = _ALPHA.copy()
    bad[0, 0] = 0.0
    with pytest.raises(ValueError, match="strictly positive"):
        evidential_decomposition(bad, _EVIDENCE, "cross_entropy")


def test_evidential_rejects_unsupported_loss() -> None:
    with pytest.raises(ValueError, match=r"cross_entropy.*zero_one"):
        evidential_decomposition(_ALPHA, _EVIDENCE, "squared")  # type: ignore[arg-type]


def test_evidential_rejects_wrong_alpha_ndim() -> None:
    with pytest.raises(ValueError, match="2-D"):
        evidential_decomposition(np.ones(3), _EVIDENCE, "cross_entropy")


def test_evidential_rejects_evidence_length_mismatch() -> None:
    with pytest.raises(ValueError, match="length"):
        evidential_decomposition(_ALPHA, np.zeros(4), "cross_entropy")


def test_evidential_rejects_nan_alpha() -> None:
    bad = _ALPHA.copy()
    bad[0, 0] = float("nan")
    with pytest.raises(ValueError, match="finite"):
        evidential_decomposition(bad, _EVIDENCE, "cross_entropy")


# ---------------------------------------------------------------------------
# Schema dispatcher round-trip
# ---------------------------------------------------------------------------


def test_dispatcher_routes_evidential_alpha_cross_entropy() -> None:
    out_direct = evidential_decomposition(_ALPHA, _EVIDENCE, "cross_entropy")
    out_dispatch = decompose_from_schema(
        {"alpha": _ALPHA, "evidence": _EVIDENCE},
        "cross_entropy",
        np.arange(3, dtype=np.float64),
        schema="evidential_alpha",
    )
    np.testing.assert_array_equal(out_dispatch["A_hat"], out_direct["A_hat"])
    np.testing.assert_array_equal(out_dispatch["E_hat"], out_direct["E_hat"])
    np.testing.assert_array_equal(out_dispatch["H_hat"], out_direct["H_hat"])


def test_dispatcher_routes_evidential_alpha_zero_one() -> None:
    out_direct = evidential_decomposition(_ALPHA, _EVIDENCE, "zero_one")
    out_dispatch = decompose_from_schema(
        {"alpha": _ALPHA, "evidence": _EVIDENCE},
        "zero_one",
        np.arange(3, dtype=np.float64),
        schema="evidential_alpha",
    )
    np.testing.assert_array_equal(out_dispatch["A_hat"], out_direct["A_hat"])
    np.testing.assert_array_equal(out_dispatch["E_hat"], out_direct["E_hat"])
    np.testing.assert_array_equal(out_dispatch["H_hat"], out_direct["H_hat"])


def test_dispatcher_evidential_alpha_missing_keys_raises() -> None:
    with pytest.raises(ValueError, match=r"alpha.*evidence"):
        decompose_from_schema(
            {"alpha": _ALPHA},  # missing 'evidence'
            "cross_entropy",
            np.arange(3, dtype=np.float64),
            schema="evidential_alpha",
        )


def test_output_schema_alias_lists_evidential() -> None:
    """Sanity check: `evidential_alpha` is in the locked schema set."""
    assert "evidential_alpha" in OutputSchema.__args__  # type: ignore[attr-defined]
