"""Hand-checked tests for the evidential-classification decomposition.

The fixture has 5 points and ``K=3``. Expected ``A_hat`` / ``E_hat``
values were generated by running the closed-form formulae through
``numpy``/``math.log`` and locking the resulting ``repr()`` strings
in this file. A regression in the formulae or in the wrapper will
fail one of these to ``atol=1e-6``.

Decomposition under test (Sensoy et al. 2018):

    alpha_0 = sum_k alpha[k]
    p_hat = alpha / alpha_0
    E_hat = K / alpha_0                                 (mass-based epistemic)
    cross_entropy:
        A_hat = -sum_k p_hat[k] log p_hat[k]            (entropy in nats)
        H_hat = p_hat                                    (soft (N, K))
    zero_one:
        A_hat = 1 - max_k p_hat[k]
        H_hat = argmax_k p_hat[k]                        (hard (N,) int64)
"""

from __future__ import annotations

import numpy as np
import pytest

from probly.quantification.decomposition import (
    OutputSchema,
    decompose_from_schema,
    evidential_decomposition,
)

# ---------------------------------------------------------------------------
# Fixture: 5 points, K=3.
#
#   i=0  alpha=[10, 1, 1]    -> alpha_0=12,  p_hat=[10/12, 1/12, 1/12]
#   i=1  alpha=[1, 1, 1]     -> alpha_0=3,   p_hat uniform
#   i=2  alpha=[100,100,100] -> alpha_0=300, p_hat uniform
#   i=3  alpha=[50, 49, 1]   -> alpha_0=100, p_hat=[0.50, 0.49, 0.01]
#   i=4  alpha=[2, 2, 2]     -> alpha_0=6,   p_hat uniform
# ---------------------------------------------------------------------------

_ALPHA = np.array(
    [
        [10.0, 1.0, 1.0],
        [1.0, 1.0, 1.0],
        [100.0, 100.0, 100.0],
        [50.0, 49.0, 1.0],
        [2.0, 2.0, 2.0],
    ],
    dtype=np.float64,
)
# evidence = alpha_0 - K (the softplus(logit) sum). Cached only;
# unused in the decomposition formulas. We pass it through to verify
# the dispatcher accepts it without entering the math.
_EVIDENCE = _ALPHA.sum(axis=1) - _ALPHA.shape[1]

_EXPECTED_E_HAT = np.array(
    [0.25, 1.0, 0.01, 0.03, 0.5],
    dtype=np.float32,
)

# Cross-entropy A_hat is the categorical entropy of p_hat (in nats).
# Values locked from `numpy`'s computation; any drift > atol=1e-6 is
# a regression.
_EXPECTED_A_HAT_CE = np.array(
    [
        0.5660857389596289,  # -((10/12)ln(10/12) + 2*(1/12)ln(1/12))
        1.0986122886681096,  # ln(3)
        1.0986122886681096,  # ln(3)
        0.7421667371998113,  # -(0.50 ln 0.50 + 0.49 ln 0.49 + 0.01 ln 0.01)
        1.0986122886681096,  # ln(3)
    ],
    dtype=np.float64,
)

# Zero-one A_hat = 1 - max_k p_hat[k]. argmax tie-break: numpy's smallest
# index (0 for the uniform fixtures).
_EXPECTED_A_HAT_ZO = np.array(
    [
        1.0 - 10.0 / 12.0,  # = 1/6
        2.0 / 3.0,  # uniform: 1 - 1/3
        2.0 / 3.0,
        0.50,  # 1 - 0.50
        2.0 / 3.0,
    ],
    dtype=np.float64,
)
_EXPECTED_H_HAT_ZO = np.array([0, 0, 0, 0, 0], dtype=np.int64)

# H_hat for cross-entropy is the soft p_hat array.
_EXPECTED_H_HAT_CE = (_ALPHA / _ALPHA.sum(axis=1, keepdims=True)).astype(np.float32)


# ---------------------------------------------------------------------------
# Direct-call tests
# ---------------------------------------------------------------------------


def test_evidential_cross_entropy_matches_locked_values() -> None:
    out = evidential_decomposition(_ALPHA, _EVIDENCE, "cross_entropy")
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.float32
    assert out["A_hat"].shape == (5,)
    assert out["E_hat"].shape == (5,)
    assert out["H_hat"].shape == (5, 3)
    np.testing.assert_allclose(out["A_hat"], _EXPECTED_A_HAT_CE, atol=1e-6)
    np.testing.assert_allclose(out["E_hat"], _EXPECTED_E_HAT, atol=1e-6)
    np.testing.assert_allclose(out["H_hat"], _EXPECTED_H_HAT_CE, atol=1e-6)


def test_evidential_zero_one_matches_locked_values() -> None:
    out = evidential_decomposition(_ALPHA, _EVIDENCE, "zero_one")
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.int64
    assert out["A_hat"].shape == (5,)
    assert out["E_hat"].shape == (5,)
    assert out["H_hat"].shape == (5,)
    np.testing.assert_allclose(out["A_hat"], _EXPECTED_A_HAT_ZO, atol=1e-6)
    np.testing.assert_allclose(out["E_hat"], _EXPECTED_E_HAT, atol=1e-6)
    np.testing.assert_array_equal(out["H_hat"], _EXPECTED_H_HAT_ZO)


def test_evidential_zero_one_argmax_tiebreak_uses_smallest_index() -> None:
    """Locked: argmax tie-break follows ``numpy.argmax`` (smallest index).

    Three of the five fixture points are uniform (alpha rows
    ``[1,1,1]``, ``[100,100,100]``, ``[2,2,2]``); their ``H_hat``
    must be 0 by the smallest-index convention.
    """
    out = evidential_decomposition(_ALPHA, _EVIDENCE, "zero_one")
    np.testing.assert_array_equal(out["H_hat"][[1, 2, 4]], np.array([0, 0, 0]))


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def test_evidential_rejects_non_positive_alpha() -> None:
    bad = _ALPHA.copy()
    bad[0, 0] = 0.0
    with pytest.raises(ValueError, match="strictly positive"):
        evidential_decomposition(bad, _EVIDENCE, "cross_entropy")


def test_evidential_rejects_unsupported_loss() -> None:
    with pytest.raises(
        ValueError, match=r"cross_entropy.*zero_one.*squared.*absolute"
    ):
        evidential_decomposition(_ALPHA, _EVIDENCE, "lbfgs")  # type: ignore[arg-type]


def test_evidential_squared_requires_support() -> None:
    with pytest.raises(ValueError, match="`support` is required"):
        evidential_decomposition(_ALPHA, _EVIDENCE, "squared")


def test_evidential_squared_closed_form() -> None:
    """Hand-checked squared decomposition on the K=3 fixture.

    For row i=0 (alpha=[10, 1, 1], support=[0, 1, 2]):
      mu = [10/12, 1/12, 1/12]
      H_hat = 0*10/12 + 1*1/12 + 2*1/12 = 3/12 = 0.25
      Var_p[y] = 0 + 1*(1/12) + 4*(1/12) - 0.0625 = 5/12 - 1/16 = 0.41666... - 0.0625 = 0.354166...
      alpha_0 = 12; A_hat = Var_p * 12/13 ; E_hat = Var_p / 13.
      A_hat + E_hat = Var_p exactly (additivity).
    """
    support = np.array([0.0, 1.0, 2.0], dtype=np.float64)
    out = evidential_decomposition(
        _ALPHA, _EVIDENCE, "squared", support=support
    )
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.float32
    assert out["A_hat"].shape == (5,)
    assert out["E_hat"].shape == (5,)
    assert out["H_hat"].shape == (5,)
    # Row 0:
    np.testing.assert_allclose(out["H_hat"][0], 3.0 / 12.0, atol=1e-6)
    var_p_0 = (1.0 / 12.0) * 1 + (1.0 / 12.0) * 4 - (3.0 / 12.0) ** 2
    np.testing.assert_allclose(
        out["A_hat"][0], var_p_0 * 12.0 / 13.0, atol=1e-6
    )
    np.testing.assert_allclose(out["E_hat"][0], var_p_0 / 13.0, atol=1e-6)
    # Row 1 (uniform alpha=[1,1,1]): mu=[1/3,1/3,1/3]; H_hat=1.0;
    # Var_p[y] = 1*(1/3) + 4*(1/3) - 1 = 5/3 - 1 = 2/3.
    np.testing.assert_allclose(out["H_hat"][1], 1.0, atol=1e-6)
    var_p_1 = 2.0 / 3.0
    np.testing.assert_allclose(
        out["A_hat"][1], var_p_1 * 3.0 / 4.0, atol=1e-6
    )
    np.testing.assert_allclose(out["E_hat"][1], var_p_1 / 4.0, atol=1e-6)
    # Additivity (T* = A* + E*) per row.
    var_p_all = np.array(
        [
            var_p_0,
            2.0 / 3.0,
            2.0 / 3.0,
            (1.0 * 0.49 + 4.0 * 0.01) - (0.49 + 0.02) ** 2,
            2.0 / 3.0,
        ]
    )
    np.testing.assert_allclose(
        out["A_hat"] + out["E_hat"], var_p_all.astype(np.float32), atol=5e-6
    )


def test_evidential_absolute_basic_contract() -> None:
    """Sample-based absolute decomp returns the right shapes + dtypes.

    The closed-form check is harder for absolute (median is non-smooth)
    so we just pin shape + dtype + nonnegativity + h_hat-in-support.
    Determinism is verified separately.

    H_hat is the BMA-median VALUE in support units (float32), matching
    the ``logits_nks`` regression decomposition's contract -- not the
    index, despite the index being what we compute internally.
    """
    support = np.array([0.0, 1.0, 2.0], dtype=np.float64)
    out = evidential_decomposition(
        _ALPHA, _EVIDENCE, "absolute", support=support
    )
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.float32
    assert out["A_hat"].shape == (5,)
    assert out["E_hat"].shape == (5,)
    assert out["H_hat"].shape == (5,)
    assert (out["A_hat"] >= 0.0).all()
    assert (out["E_hat"] >= 0.0).all()
    # H_hat is the median VALUE; for a 3-point support it must be in {0, 1, 2}.
    assert np.isin(out["H_hat"], support.astype(np.float32)).all()


def test_evidential_absolute_is_deterministic() -> None:
    """Two consecutive calls produce bit-identical outputs.

    Pin: the Dirichlet sampler uses ``_ABSOLUTE_SAMPLE_SEED`` (fixed),
    so the cache hash is a pure function of inputs.
    """
    support = np.array([0.0, 1.0, 2.0], dtype=np.float64)
    a = evidential_decomposition(_ALPHA, _EVIDENCE, "absolute", support=support)
    b = evidential_decomposition(_ALPHA, _EVIDENCE, "absolute", support=support)
    np.testing.assert_array_equal(a["A_hat"], b["A_hat"])
    np.testing.assert_array_equal(a["E_hat"], b["E_hat"])
    np.testing.assert_array_equal(a["H_hat"], b["H_hat"])


def test_dispatcher_routes_evidential_alpha_squared() -> None:
    support = np.arange(3, dtype=np.float64)
    out_direct = evidential_decomposition(
        _ALPHA, _EVIDENCE, "squared", support=support
    )
    out_dispatch = decompose_from_schema(
        {"alpha": _ALPHA, "evidence": _EVIDENCE},
        "squared",
        support,
        schema="evidential_alpha",
    )
    np.testing.assert_array_equal(out_dispatch["A_hat"], out_direct["A_hat"])
    np.testing.assert_array_equal(out_dispatch["E_hat"], out_direct["E_hat"])
    np.testing.assert_array_equal(out_dispatch["H_hat"], out_direct["H_hat"])


def test_dispatcher_routes_evidential_alpha_absolute() -> None:
    support = np.arange(3, dtype=np.float64)
    out_direct = evidential_decomposition(
        _ALPHA, _EVIDENCE, "absolute", support=support
    )
    out_dispatch = decompose_from_schema(
        {"alpha": _ALPHA, "evidence": _EVIDENCE},
        "absolute",
        support,
        schema="evidential_alpha",
    )
    np.testing.assert_array_equal(out_dispatch["A_hat"], out_direct["A_hat"])
    np.testing.assert_array_equal(out_dispatch["E_hat"], out_direct["E_hat"])
    np.testing.assert_array_equal(out_dispatch["H_hat"], out_direct["H_hat"])


def test_evidential_rejects_wrong_alpha_ndim() -> None:
    with pytest.raises(ValueError, match="2-D"):
        evidential_decomposition(np.ones(3), _EVIDENCE, "cross_entropy")


def test_evidential_rejects_evidence_length_mismatch() -> None:
    with pytest.raises(ValueError, match="length"):
        evidential_decomposition(_ALPHA, np.zeros(4), "cross_entropy")


def test_evidential_rejects_nan_alpha() -> None:
    bad = _ALPHA.copy()
    bad[0, 0] = float("nan")
    with pytest.raises(ValueError, match="finite"):
        evidential_decomposition(bad, _EVIDENCE, "cross_entropy")


# ---------------------------------------------------------------------------
# Schema dispatcher round-trip
# ---------------------------------------------------------------------------


def test_dispatcher_routes_evidential_alpha_cross_entropy() -> None:
    out_direct = evidential_decomposition(_ALPHA, _EVIDENCE, "cross_entropy")
    out_dispatch = decompose_from_schema(
        {"alpha": _ALPHA, "evidence": _EVIDENCE},
        "cross_entropy",
        np.arange(3, dtype=np.float64),
        schema="evidential_alpha",
    )
    np.testing.assert_array_equal(out_dispatch["A_hat"], out_direct["A_hat"])
    np.testing.assert_array_equal(out_dispatch["E_hat"], out_direct["E_hat"])
    np.testing.assert_array_equal(out_dispatch["H_hat"], out_direct["H_hat"])


def test_dispatcher_routes_evidential_alpha_zero_one() -> None:
    out_direct = evidential_decomposition(_ALPHA, _EVIDENCE, "zero_one")
    out_dispatch = decompose_from_schema(
        {"alpha": _ALPHA, "evidence": _EVIDENCE},
        "zero_one",
        np.arange(3, dtype=np.float64),
        schema="evidential_alpha",
    )
    np.testing.assert_array_equal(out_dispatch["A_hat"], out_direct["A_hat"])
    np.testing.assert_array_equal(out_dispatch["E_hat"], out_direct["E_hat"])
    np.testing.assert_array_equal(out_dispatch["H_hat"], out_direct["H_hat"])


def test_dispatcher_evidential_alpha_missing_keys_raises() -> None:
    with pytest.raises(ValueError, match=r"alpha.*evidence"):
        decompose_from_schema(
            {"alpha": _ALPHA},  # missing 'evidence'
            "cross_entropy",
            np.arange(3, dtype=np.float64),
            schema="evidential_alpha",
        )


def test_output_schema_alias_lists_evidential() -> None:
    """Sanity check: `evidential_alpha` is in the locked schema set."""
    assert "evidential_alpha" in OutputSchema.__args__  # type: ignore[attr-defined]
