"""Hand-checked tests for the DDU decomposition.

The fixture has 4 points and ``K=3``. Expected ``A_hat`` / ``E_hat``
values were generated by running the closed-form formulae through
``numpy``/``math.log`` and locking the resulting ``repr()`` strings
in this file. A regression in the formulae or in the wrapper will
fail one of these to ``atol=1e-6``.

Decomposition under test (Mukhoti et al. 2023):

    cross_entropy:
        A_hat = -sum_k probs[k] log probs[k]            (entropy in nats)
        H_hat = probs                                    (soft (N, K))
    zero_one:
        A_hat = 1 - max_k probs[k]
        H_hat = argmax_k probs[k]                        (hard (N,) int64)
    E_hat = -density                                     (negate so HIGHER -> MORE OOD)
"""

from __future__ import annotations

import numpy as np
import pytest

from probly.quantification.decomposition import (
    OutputSchema,
    ddu_decomposition,
    decompose_from_schema,
)

# ---------------------------------------------------------------------------
# Fixture: 4 points, K=3.
#
#   i=0  probs=[0.7, 0.2, 0.1]      density=-2.0  (in-distribution-ish)
#   i=1  probs=[1/3, 1/3, 1/3]      density=-10.0 (OOD-est by density)
#   i=2  probs=[0.9, 0.05, 0.05]    density=-1.5  (most in-distribution)
#   i=3  probs=[0.4, 0.3, 0.3]      density=-5.0
# ---------------------------------------------------------------------------

_PROBS = np.array(
    [
        [0.7, 0.2, 0.1],
        [1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0],
        [0.9, 0.05, 0.05],
        [0.4, 0.3, 0.3],
    ],
    dtype=np.float64,
)
_DENSITY = np.array([-2.0, -10.0, -1.5, -5.0], dtype=np.float64)

_EXPECTED_E_HAT = np.array([2.0, 10.0, 1.5, 5.0], dtype=np.float32)

# Cross-entropy A_hat values, locked from `numpy`'s computation.
_EXPECTED_A_HAT_CE = np.array(
    [
        0.8018185525433372,  # -(0.7 ln 0.7 + 0.2 ln 0.2 + 0.1 ln 0.1)
        1.0986122886681096,  # ln(3)
        0.39439769144744274,  # -(0.9 ln 0.9 + 2 * 0.05 ln 0.05)
        1.0888999753452238,  # -(0.4 ln 0.4 + 2 * 0.3 ln 0.3)
    ],
    dtype=np.float64,
)

_EXPECTED_A_HAT_ZO = np.array(
    [
        1.0 - 0.7,
        1.0 - 1.0 / 3.0,
        1.0 - 0.9,
        1.0 - 0.4,
    ],
    dtype=np.float64,
)
_EXPECTED_H_HAT_ZO = np.array([0, 0, 0, 0], dtype=np.int64)
_EXPECTED_H_HAT_CE = _PROBS.astype(np.float32)


# ---------------------------------------------------------------------------
# Direct-call tests
# ---------------------------------------------------------------------------


def test_ddu_cross_entropy_matches_locked_values() -> None:
    out = ddu_decomposition(_PROBS, _DENSITY, "cross_entropy")
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.float32
    assert out["A_hat"].shape == (4,)
    assert out["E_hat"].shape == (4,)
    assert out["H_hat"].shape == (4, 3)
    np.testing.assert_allclose(out["A_hat"], _EXPECTED_A_HAT_CE, atol=1e-6)
    np.testing.assert_allclose(out["E_hat"], _EXPECTED_E_HAT, atol=1e-6)
    np.testing.assert_allclose(out["H_hat"], _EXPECTED_H_HAT_CE, atol=1e-6)


def test_ddu_zero_one_matches_locked_values() -> None:
    out = ddu_decomposition(_PROBS, _DENSITY, "zero_one")
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.int64
    assert out["A_hat"].shape == (4,)
    assert out["E_hat"].shape == (4,)
    assert out["H_hat"].shape == (4,)
    np.testing.assert_allclose(out["A_hat"], _EXPECTED_A_HAT_ZO, atol=1e-6)
    np.testing.assert_allclose(out["E_hat"], _EXPECTED_E_HAT, atol=1e-6)
    np.testing.assert_array_equal(out["H_hat"], _EXPECTED_H_HAT_ZO)


def test_ddu_e_hat_is_monotone_in_ood() -> None:
    """The OOD-est point (lowest density) gets the highest E_hat."""
    out = ddu_decomposition(_PROBS, _DENSITY, "cross_entropy")
    # i=1 has density -10 (most OOD); E_hat[1] should be the largest.
    assert out["E_hat"].argmax() == 1
    # i=2 has density -1.5 (most in-distribution); E_hat[2] should be smallest.
    assert out["E_hat"].argmin() == 2


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def test_ddu_rejects_non_row_stochastic_probs() -> None:
    bad = _PROBS.copy()
    bad[0, :] = [0.5, 0.5, 0.5]  # sums to 1.5
    with pytest.raises(ValueError, match="rows must sum to 1"):
        ddu_decomposition(bad, _DENSITY, "cross_entropy")


def test_ddu_rejects_negative_probs() -> None:
    bad = _PROBS.copy()
    bad[0, 0] = -0.1
    bad[0, 1] = 1.0  # keep row sum at 1.0 (= 1.0 + 0.1 - 0.1 + 0.1 ok, but check non-negativity)
    bad[0, 2] = 0.0
    bad[0] = bad[0] / bad[0].sum() if bad[0].sum() > 0 else bad[0]
    bad[0, 0] = -0.1  # restore the negative entry
    bad[0, 1] = 1.0
    bad[0, 2] = 0.1
    # row sums to 1.0 but has a negative entry
    with pytest.raises(ValueError, match="non-negative"):
        ddu_decomposition(bad, _DENSITY, "cross_entropy")


def test_ddu_rejects_unsupported_loss() -> None:
    """Unknown loss strings raise (not just unsupported deployment losses)."""
    with pytest.raises(
        ValueError, match=r"cross_entropy.*zero_one.*squared.*absolute"
    ):
        ddu_decomposition(_PROBS, _DENSITY, "lbfgs")  # type: ignore[arg-type]


def test_ddu_squared_requires_support() -> None:
    with pytest.raises(ValueError, match="`support` is required"):
        ddu_decomposition(_PROBS, _DENSITY, "squared")


def test_ddu_squared_decomposition_basic_contract() -> None:
    """Squared returns (mean, variance, density) per row.

    H_hat[i] = sum_k support[k] * probs[i, k]
    A_hat[i] = Var_p[y]
    E_hat[i] = -density[i]  (unchanged from classification branches)
    """
    support = np.array([0.0, 10.0, 20.0], dtype=np.float64)  # K=3 fixture
    out = ddu_decomposition(_PROBS, _DENSITY, "squared", support=support)
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.float32
    n = _PROBS.shape[0]
    assert out["A_hat"].shape == (n,)
    # H_hat is the mean predictor; bounded by min/max of support.
    assert (out["H_hat"] >= support[0] - 1e-6).all()
    assert (out["H_hat"] <= support[-1] + 1e-6).all()
    # E_hat unchanged from cross_entropy / zero_one branches.
    np.testing.assert_allclose(out["E_hat"], -_DENSITY.astype(np.float32))


def test_ddu_absolute_decomposition_basic_contract() -> None:
    """Absolute returns (median value in support, MAD around median, density).

    H_hat is the median VALUE in support units (float32) — matching the
    ``logits_nks`` regression contract — not the index.
    """
    support = np.array([0.0, 10.0, 20.0], dtype=np.float64)
    out = ddu_decomposition(_PROBS, _DENSITY, "absolute", support=support)
    assert out["A_hat"].dtype == np.float32
    assert out["E_hat"].dtype == np.float32
    assert out["H_hat"].dtype == np.float32
    # H_hat is the median VALUE; for a 3-point support {0,10,20} it must
    # be one of those.
    assert np.isin(out["H_hat"], support.astype(np.float32)).all()
    np.testing.assert_allclose(out["E_hat"], -_DENSITY.astype(np.float32))


def test_ddu_rejects_density_length_mismatch() -> None:
    with pytest.raises(ValueError, match="length"):
        ddu_decomposition(_PROBS, np.zeros(7), "cross_entropy")


def test_ddu_rejects_nan_density() -> None:
    bad = _DENSITY.copy()
    bad[0] = float("nan")
    with pytest.raises(ValueError, match="finite"):
        ddu_decomposition(_PROBS, bad, "cross_entropy")


# ---------------------------------------------------------------------------
# Schema dispatcher round-trip
# ---------------------------------------------------------------------------


def test_dispatcher_routes_ddu_cross_entropy() -> None:
    out_direct = ddu_decomposition(_PROBS, _DENSITY, "cross_entropy")
    out_dispatch = decompose_from_schema(
        {"probs": _PROBS, "density": _DENSITY},
        "cross_entropy",
        np.arange(3, dtype=np.float64),
        schema="ddu_probs_density",
    )
    np.testing.assert_array_equal(out_dispatch["A_hat"], out_direct["A_hat"])
    np.testing.assert_array_equal(out_dispatch["E_hat"], out_direct["E_hat"])
    np.testing.assert_array_equal(out_dispatch["H_hat"], out_direct["H_hat"])


def test_dispatcher_routes_ddu_zero_one() -> None:
    out_direct = ddu_decomposition(_PROBS, _DENSITY, "zero_one")
    out_dispatch = decompose_from_schema(
        {"probs": _PROBS, "density": _DENSITY},
        "zero_one",
        np.arange(3, dtype=np.float64),
        schema="ddu_probs_density",
    )
    np.testing.assert_array_equal(out_dispatch["A_hat"], out_direct["A_hat"])
    np.testing.assert_array_equal(out_dispatch["E_hat"], out_direct["E_hat"])
    np.testing.assert_array_equal(out_dispatch["H_hat"], out_direct["H_hat"])


def test_dispatcher_ddu_missing_keys_raises() -> None:
    with pytest.raises(ValueError, match=r"probs.*density"):
        decompose_from_schema(
            {"probs": _PROBS},  # missing 'density'
            "cross_entropy",
            np.arange(3, dtype=np.float64),
            schema="ddu_probs_density",
        )


def test_dispatcher_unknown_schema_raises() -> None:
    with pytest.raises(ValueError, match="unknown output_schema"):
        decompose_from_schema(
            {"foo": np.zeros((4, 3))},
            "cross_entropy",
            np.arange(3, dtype=np.float64),
            schema="not_a_real_schema",  # type: ignore[arg-type]
        )


def test_output_schema_alias_lists_ddu() -> None:
    """Sanity check: `ddu_probs_density` is in the locked schema set."""
    assert "ddu_probs_density" in OutputSchema.__args__  # type: ignore[attr-defined]
